name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install GRASS GIS
      run: |
        sudo add-apt-repository --yes ppa:ubuntugis/ubuntugis-unstable
        sudo apt-get update
        sudo apt-get install --yes grass grass-dev
    - name: Test GRASS GIS
      run: |
        grass --tmp-location XY --exec g.version -e
    - name: Cache sample data
      id: cache-nc_spm_08_grass7
      uses: actions/cache@v1
      with:
        path: nc_spm_08_grass7
        key: ${{ runner.os }}-nc_spm_08_grass7
    - name: Get sample data
      if: steps.cache-nc_spm_08_grass7.outputs.cache-hit != 'true'
      run: |
        grass --tmp-location XY --exec g.extension g.download.location --verbose
        grass --tmp-location XY --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz dbase=. --verbose
    - name: Test execution of Python files
      run: |
        python3 ./tests/functions.py

  content:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Test content structure of Python files
      run: |
        python3 ./tests/functions_format.py
    - name: Test content structure of JSON files
      run: |
        python3 ./tests/json_structure.py

  code:

    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Check code with Flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
